# Copyright (c) 2013 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when toolkit is run from outside a project.

#################################################################################################
# define all the items that should appear in this environment
# By default make the non-project side of the desktop engine available

engines:
  tk-rv:
    apps:
      tk-multi-pythonconsole:
        location:
          type: git
          path: https://github.com/josh-t/tk-multi-pythonconsole.git
          version: v1.0.2
      tk-rv-shotgunreview:
        location:
          # type: dev
          # path: d:\repositories\tk-rv-shotgunreview
          # name: tk-rv-shotgunreview
          path: 'git@github.com:shotgunsoftware/tk-rv-shotgunreview.git'
          type: git_branch
          branch: master
          version: f37e8e3ddf971f2fcd5fd90d991be532e08d4502
      tk-multi-importcut:
          cut_link_field: sg_entity
          default_head_in: 1001
          default_head_in_duration: 8
          default_tail_out_duration: 8
          display_name: Import Cut
          ensure_sg_setup_hook: '{self}/post_install.py'
          location:
            # name: tk-multi-importcut
            # type: app_store
            # version: v1.3.0
            path: 'git@github.com:shotgunsoftware/tk-multi-importcut.git'
            type: git_branch
            branch: master
            version: d087806106b9d0a2c530dcc944fdf4873fb1ed26
            # type: dev
            # path: d:\repositories\tk-multi-importcut
          omit_statuses: [inac, hld, omt]
          reinstate_status: ip
          report_to_group: Editorial
          sg_cut_item_entity: CutItem
          use_smart_fields: true
          timecode_frame_mapping:
              timecode: "automatic"
              frame: 1001
    menu_overrides:
      SG Review:
        - {app_instance: tk-multi-importcut, name: Import Cut}
      Tools:
        - {app_instance: tk-multi-pythonconsole, name: Shotgun Python Console...}
    debug_logging: false
    location:
      # type: dev
      # path: d:\repositories\tk-rv
      name: tk-rv
      path: 'git@github.com:shotgunsoftware/tk-rv.git'
      type: git_branch
      branch: master
      version: 26d94cc1f4c3a6ade17ad987dd33bc731d28e9d6


frameworks:
  tk-framework-qtwidgets_v2.x.x:
    location:
      type: git_branch
      path: git@github.com:shotgunsoftware/tk-framework-qtwidgets.git
      branch: 34751_rv_shotgunreview
      version: 9bdc5a7fab0b9d6afd7c88768f4b3ddef6379bc2
  tk-framework-shotgunutils_v4.x.x:
    location:
      type: git_branch
      path: git@github.com:shotgunsoftware/tk-framework-shotgunutils.git
      branch: master
      version: a84442d8d6e84030a22545fd59824341b9a14e2b
  tk-framework-editorial_v1.x.x:
    location: {name: tk-framework-editorial, type: app_store, version: v1.2.1}

