# Copyright (c) 2013 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when toolkit is run from outside a project.

#################################################################################################
# define all the items that should appear in this environment
# By default make the non-project side of the desktop engine available

engines:
  tk-rv:
    apps:
      tk-multi-about:
        location:
          name: tk-multi-about
          type: app_store
          version: v0.2.0
      tk-rv-shotgunreview:
        location:
          # type: dev
          # path: d:\repositories\tk-rv-shotgunreview
          # name: tk-rv-shotgunreview
          path: 'git@github.com:shotgunsoftware/tk-rv-shotgunreview.git'
          type: git_branch
          branch: master
          # version: latest
          version: e9901720735d11ddba3093d58e1fcbc1bac46df6
      tk-multi-importcut:
          cut_link_field: sg_entity
          default_head_in: 1001
          default_head_in_duration: 8
          default_tail_out_duration: 8
          display_name: Cut Import
          ensure_sg_setup_hook: '{self}/post_install.py'
          location:
            # name: tk-multi-importcut
            # type: app_store
            # version: v1.3.0
            path: 'git@github.com:shotgunsoftware/tk-multi-importcut.git'
            type: git_branch
            branch: nab_features_2016
            version: 3814baf7075b386fedaaa748d1cf1a21b5649fa8
            # type: dev
            # path: d:\repositories\tk-multi-importcut
          omit_statuses: [inac, hld, omt]
          reinstate_status: ip
          report_to_group: Editorial
          sg_cut_item_entity: CutItem
          use_smart_fields: true
          timecode_frame_mapping:
              timecode: "automatic"
              frame: 1001
    debug_logging: false
    location:
      # type: dev
      # path: d:\repositories\tk-rv
      name: tk-rv
      path: 'git@github.com:shotgunsoftware/tk-rv.git'
      type: git_branch
      branch: master
      # version: latest
      version: 4f8dd6bf6f5f4b457b380035493eec9895b09593


frameworks:
  tk-framework-qtwidgets_v2.x.x:
    location:
      type: git_branch
      path: git@github.com:shotgunsoftware/tk-framework-qtwidgets.git
      branch: 34751_rv_shotgunreview
      # version: latest
      version: 5ec5944499a1ad409a3e5b99e18ed2accb46f1cd
  tk-framework-shotgunutils_v4.x.x:
    location:
      type: git_branch
      path: git@github.com:shotgunsoftware/tk-framework-shotgunutils.git
      branch: master
      # version: latest
      version: 353867bedd36619e9034f7188de4f716f3ee9fab
  tk-framework-editorial_v1.x.x:
    location: {name: tk-framework-editorial, type: app_store, version: v1.2.1}

