# Copyright (c) 2013 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when toolkit is run from outside a project.

#################################################################################################
# define all the items that should appear in this environment
# By default make the non-project side of the desktop engine available

engines:
  tk-rv:
    apps:
      tk-multi-about:
        location:
          name: tk-multi-about
          type: app_store
          version: v0.2.0
      tk-rv-shotgunreview:
        location:
          # type: dev
          # path: d:\repositories\tk-rv-shotgunreview
          # name: tk-rv-shotgunreview
          path: 'git@github.com:shotgunsoftware/tk-rv-shotgunreview.git'
          type: git_branch
          branch: master
          version: latest
      tk-multi-importcut:
          cut_link_field: sg_entity
          default_head_in: 1001
          default_head_in_duration: 8
          default_tail_out_duration: 8
          display_name: Cut Import
          ensure_sg_setup_hook: '{self}/post_install.py'
          location:
            # name: tk-multi-importcut
            # type: app_store
            # version: v1.3.0
            path: 'git@github.com:shotgunsoftware/tk-multi-importcut.git'
            type: git_branch
            branch: 34904_rv_bootstrap
            version: c3257622294cd2d4b63075830a37ba07265c189f
            # type: dev
            # path: d:\repositories\tk-multi-importcut
          omit_statuses: [inac, hld, omt]
          reinstate_status: ip
          report_to_group: Editorial
          sg_cut_item_entity: CutItem
          use_smart_fields: true
          timecode_frame_mapping:
              timecode: "automatic"
              frame: 1001
    debug_logging: false
    location:
      # type: dev
      # path: d:\repositories\tk-rv
      name: tk-rv
      path: 'git@github.com:shotgunsoftware/tk-rv.git'
      type: git_branch
      branch: master
      version: latest

# note! The login framework is included for backwards compatibility with 
# some apps that are running in desktop, so although it is not strictly
# required anymore for the desktop system itself to run correctly,
# we included here to ensure correct overall operation.
frameworks:

  tk-framework-widget_v0.2.x:
    location: {name: tk-framework-widget, type: app_store, version: v0.2.3}
  tk-framework-qtwidgets_v2.x.x:
    location:
      type: git_branch
      path: git@github.com:shotgunsoftware/tk-framework-qtwidgets.git
      branch: 34751_rv_shotgunreview
      version: latest
  tk-framework-qtwidgets_v1.x.x:
    location:
      type: git_branch
      path: git@github.com:shotgunsoftware/tk-framework-qtwidgets.git
      branch: 34751_rv_shotgunreview
      version: latest
  tk-framework-shotgunutils_v2.x.x:
    location:
      type: git_branch
      path: git@github.com:shotgunsoftware/tk-framework-shotgunutils.git
      branch: master
      version: latest
  tk-framework-shotgunutils_v4.x.x:
    location:
      type: git_branch
      path: git@github.com:shotgunsoftware/tk-framework-shotgunutils.git
      branch: master
      version: latest
  tk-framework-pi_v0.x.x:
    location: {name: tk-framework-pi, type: app_store, version: v0.0.1}
  tk-framework-editorial_v1.x.x:
    location: {name: tk-framework-editorial, type: app_store, version: v1.2.1}
  tk-framework-wb_v3.x.x:
    location: {name: tk-framework-wb, type: app_store, version: v3.4.0}
  tk-framework-studio_v1.x.x:
    location: {name: tk-framework-studio, type: app_store, version: v1.2.5}
  tk-framework-transcoding_v1.x.x:
    location: {name: tk-framework-transcoding, type: app_store, version: v1.3.0}
  tk-framework-delivery_v1.x.x:
    delivery_formats:
    - display_name: Images
      exclusive: true
      extensions: [exr, dpx, tif, tiff, jpg, jpeg, png, tga, pdf]
      name: image
      tank_type: '{EXTENSION}'
      type: image
    - display_name: Mov
      exclusive: true
      extensions: [mov, mp4, mpeg, avi]
      name: movie
      tank_type: '{EXTENSION}'
      type: movie
    - display_name: Ed
      exclusive: false
      extensions: [edit]
      name: editorial
      tank_type: DNXHD
      type: movie
    - display_name: ???
      exclusive: false
      extensions: []
      name: other
      tank_type: '{EXTENSION}'
      type: other
    location: {name: tk-framework-delivery, type: app_store, version: v1.2.2}
  tk-framework-delivery_v2.x.x:
    delivery_formats:
    - display_name: Images
      exclusive: true
      extensions: [exr, dpx, tif, tiff, jpg, jpeg, png, tga, pdf]
      name: image
      tank_type: '{EXTENSION}'
      type: image
    - display_name: Mov
      exclusive: true
      extensions: [mov, mp4, mpeg, avi]
      name: movie
      tank_type: '{EXTENSION}'
      type: movie
    - display_name: Ed
      exclusive: false
      extensions: [edit]
      name: editorial
      tank_type: DNXHD
      type: movie
    - display_name: ???
      exclusive: false
      extensions: []
      name: other
      tank_type: '{EXTENSION}'
      type: other
    location: {name: tk-framework-delivery, type: app_store, version: v2.1.2}
